### PR TITLE
I only managed to get it to work by changing the netstandard to version 2.0

### PR DESCRIPTION
**Pull request by BDisp**

### CODE REVIEW

**Comment by wgross** [comment]
Pulling this in for sure.
I had no good reason to use 2.1 except assuming it might be required by some fancy new C# stuff :-)

**Comment by BDisp** [comment]
How did you manage to run without getting an error before?

**Comment by wgross** [comment]
Did you run it with PS5? PS5 is compiled with the FullFramework 4.x which supports netstandard 2.0 only. But I'm using PS7 which uses one of the newer versions of the core framework. No problem there with netstandard2.1. 

But excluding PS5 from loading the module wasn't intended. It is definitely better to use netstandard2 as long it is possible.

**Comment by BDisp** [comment]
I really use the `PS5`.

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1
```

I prefer use the latest stable version applications to not wast time on experimental previews versions that changing a lot until the final version. That why I didn't start working with the `NET5` yet :-)

**Pull request merged**
